on:
  push:
    branches:
      - master

env:
  ResourceGroup: repo-mirror
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100
    - name: build
      run: dotnet build -c Release
    - name: test
      run: dotnet test -c Release --no-build **/*.Test*.csproj
    - name: publish
      run: dotnet publish -c Release --no-build GitMirrorAutomation.Func/GitMirrorAutomation.Func.csproj -o release/GitMirrorAutomation.Func
    - uses: actions/upload-artifact@v1
      with:
        name: deploy
        path: deploy
    - uses: actions/upload-artifact@v1
      with:
        name: functionapp
        path: release/GitMirrorAutomation.Func
  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v1
        with:
          name: functionapp
          path: functionapp
      - uses: actions/download-artifact@v1
        with:
          name: deploy
          path: deploy
      - name: Login via Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Azure CLI ARM deployment
        uses: azure/CLI@v1
        with:
          inlineScript: |
            cd deploy
            chmod +x deploy.sh
            ./deploy.sh $ResourceGroup
      - uses: azure/functions-action@v1
        with:
          app-name: ${{ env.ResourceGroup }}
          package: functionapp